# Autogenerated wrapper script for AndorSDK2_jll for x86_64-w64-mingw32-cxx11
export libandor2

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("AndorSDK2")
JLLWrappers.@declare_library_product(libandor2, "atmcd64d.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libandor2,
        "bin\\atmcd64d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
